services:
  - type: web
    name: orderflow-backend
    env: node
    repo: https://github.com/Teenoi65020980-glitch/orderflow-backend
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    rootDir: .
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: DATABASE_URL
        value: your_database_url_here
